'use strict';

// ============================================================
// Nginx Service — services/nginxService.js
// Section 8.6
//
// Manages per-project Nginx config files in NGINX_CONF_DIR.
// Static platform configs (00-upstream.conf, acadhost.com.conf,
// etc.) are NOT managed here — they are deployed manually.
//
// Per-project config template (Section 8.6.2):
//   {subdomain}.conf  — proxy_pass to student container port
//
// Functions:
//   addProjectConfig(subdomain, containerPort)
//   removeProjectConfig(subdomain)
//   removeMultipleProjectConfigs(subdomains[])
//   initializeOnStartup()
// ============================================================

const fsp     = require('fs').promises;
const path    = require('path');
const { exec } = require('child_process');
const pool    = require('../config/db');

// Static platform config filenames that must never be treated as orphans.
const STATIC_PLATFORM_CONFIGS = new Set([
  '00-upstream.conf',
  'acadhost.com.conf',
  'admin.acadhost.com.conf',
  'phpmyadmin.acadhost.com.conf',
  'default-catch-all.conf',
]);

// ── Helpers ──────────────────────────────────────────────────

/**
 * Promisified exec wrapper.  Captures stdout and stderr.
 * @param {string} cmd
 * @returns {Promise<{ stdout: string, stderr: string }>}
 */
function runCmd(cmd) {
  return new Promise((resolve, reject) => {
    exec(cmd, (err, stdout, stderr) => {
      if (err) {
        return reject(Object.assign(new Error(stderr || err.message), { stdout, stderr }));
      }
      resolve({ stdout, stderr });
    });
  });
}

/**
 * Builds the Nginx server block content for a student project.
 *
 * @param {string} subdomain
 * @param {number} containerPort
 * @returns {string}
 */
function buildConfigContent(subdomain, containerPort) {
  const domain    = process.env.PLATFORM_DOMAIN || 'acadhost.com';
  const proxyHost = process.env.NGINX_PROXY_HOST || '127.0.0.1';
  const timestamp = new Date().toISOString();

  return `# Auto-generated by nginxService.js -- DO NOT EDIT
# Project: ${subdomain} | Port: ${containerPort} | Generated: ${timestamp}

server {
    listen 80;
    server_name ${subdomain}.${domain};

    location / {
        proxy_pass http://${proxyHost}:${containerPort};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
`;
}

/**
 * Returns the full path for a project's conf file.
 * @param {string} subdomain
 * @returns {string}
 */
function confPath(subdomain) {
  return path.join(process.env.NGINX_CONF_DIR, `${subdomain}.conf`);
}

/**
 * Runs NGINX_TEST_CMD and NGINX_RELOAD_CMD in sequence.
 * Throws if the test fails.
 *
 * @param {string} [cleanupOnTestFail] — path to delete if nginx -t fails
 */
async function validateAndReload(cleanupOnTestFail) {
  const testCmd   = process.env.NGINX_TEST_CMD   || 'nginx -t';
  const reloadCmd = process.env.NGINX_RELOAD_CMD || 'nginx -s reload';

  try {
    await runCmd(testCmd);
  } catch (testErr) {
    console.error(`[nginxService] nginx config test failed: ${testErr.message}`);
    if (cleanupOnTestFail) {
      try { await fsp.unlink(cleanupOnTestFail); } catch (_) { /* ignore */ }
    }
    throw Object.assign(new Error(`Nginx config test failed: ${testErr.message}`), {
      code: 'NGINX_TEST_FAILED',
    });
  }

  try {
    await runCmd(reloadCmd);
  } catch (reloadErr) {
    console.error(`[nginxService] nginx reload failed: ${reloadErr.message}`);
    throw Object.assign(new Error(`Nginx reload failed: ${reloadErr.message}`), {
      code: 'NGINX_RELOAD_FAILED',
    });
  }
}

// ── addProjectConfig ─────────────────────────────────────────

/**
 * Writes a per-project Nginx config file and reloads Nginx.
 *
 * Atomic write algorithm (Section 8.6.6):
 *   1. Write to {subdomain}.conf.tmp
 *   2. Rename to {subdomain}.conf
 *   3. Run nginx -t — if it fails, delete the new conf and throw
 *   4. Run nginx -s reload
 *
 * @param {string} subdomain
 * @param {number} containerPort
 */
async function addProjectConfig(subdomain, containerPort) {
  const confDir  = process.env.NGINX_CONF_DIR;
  const tmpFile  = path.join(confDir, `${subdomain}.conf.tmp`);
  const destFile = confPath(subdomain);
  const content  = buildConfigContent(subdomain, containerPort);

  // Atomic write: tmp → rename
  await fsp.writeFile(tmpFile, content, 'utf8');
  await fsp.rename(tmpFile, destFile);

  // Validate; on failure the conf file is cleaned up inside validateAndReload
  await validateAndReload(destFile);
}

// ── removeProjectConfig ──────────────────────────────────────

/**
 * Deletes a per-project Nginx config file and reloads Nginx.
 * Logs a warning if the file does not exist but does not throw.
 *
 * @param {string} subdomain
 */
async function removeProjectConfig(subdomain) {
  const file = confPath(subdomain);

  try {
    await fsp.unlink(file);
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.warn(`[nginxService] removeProjectConfig: file not found (already gone?): ${file}`);
    } else {
      console.error(`[nginxService] removeProjectConfig: error deleting ${file}: ${err.message}`);
    }
  }

  const reloadCmd = process.env.NGINX_RELOAD_CMD || 'nginx -s reload';
  try {
    await runCmd(reloadCmd);
  } catch (reloadErr) {
    // Log but do not throw — the file is already deleted; next reload will succeed
    console.error(`[nginxService] Nginx reload after remove failed: ${reloadErr.message}`);
  }
}

// ── removeMultipleProjectConfigs ─────────────────────────────

/**
 * Deletes multiple per-project Nginx config files, then reloads once.
 *
 * @param {string[]} subdomains
 */
async function removeMultipleProjectConfigs(subdomains) {
  for (const subdomain of subdomains) {
    const file = confPath(subdomain);
    try {
      await fsp.unlink(file);
    } catch (err) {
      if (err.code === 'ENOENT') {
        console.warn(`[nginxService] removeMultipleProjectConfigs: file not found: ${file}`);
      } else {
        console.error(`[nginxService] Error deleting ${file}: ${err.message}`);
      }
    }
  }

  const reloadCmd = process.env.NGINX_RELOAD_CMD || 'nginx -s reload';
  try {
    await runCmd(reloadCmd);
  } catch (reloadErr) {
    console.error(`[nginxService] Nginx reload after batch remove failed: ${reloadErr.message}`);
  }
}

// ── initializeOnStartup ──────────────────────────────────────

/**
 * Synchronises NGINX_CONF_DIR with the current database state on
 * backend startup (Section 8.6.6 — initializeOnStartup algorithm).
 *
 * Steps:
 *   1. Query all active projects (non-deleted, port assigned,
 *      subdomain not renamed to _deleted_*).
 *   2. Write any missing per-project conf files.
 *   3. List all .conf files in NGINX_CONF_DIR; delete any that
 *      are not static platform configs and not active project confs.
 *   4. Run nginx -t and nginx -s reload once.
 */
async function initializeOnStartup() {
  const confDir = process.env.NGINX_CONF_DIR;

  // Step 1: query active projects
  const [rows] = await pool.query(
    `SELECT subdomain, container_port
     FROM projects
     WHERE status IN ('running', 'stopped', 'building', 'failed')
       AND container_port IS NOT NULL
       AND subdomain NOT LIKE '_deleted_%'`
  );

  // Step 2: write any missing conf files
  const activeSubdomains = new Set();
  for (const row of rows) {
    activeSubdomains.add(row.subdomain);
    const file = confPath(row.subdomain);
    try {
      await fsp.access(file);
      // File exists — no action needed
    } catch (_) {
      // File does not exist — write it
      const content = buildConfigContent(row.subdomain, row.container_port);
      await fsp.writeFile(file, content, 'utf8');
      console.info(`[nginxService] initializeOnStartup: wrote missing config for ${row.subdomain}`);
    }
  }

  // Step 3: remove orphaned conf files
  let existingFiles;
  try {
    existingFiles = await fsp.readdir(confDir);
  } catch (err) {
    console.error(`[nginxService] initializeOnStartup: cannot read NGINX_CONF_DIR ${confDir}: ${err.message}`);
    return;
  }

  for (const filename of existingFiles) {
    if (!filename.endsWith('.conf')) continue;
    if (STATIC_PLATFORM_CONFIGS.has(filename)) continue;

    // Extract subdomain from filename (strip .conf suffix)
    const subdomain = filename.slice(0, -5);
    if (!activeSubdomains.has(subdomain)) {
      const orphanPath = path.join(confDir, filename);
      try {
        await fsp.unlink(orphanPath);
        console.info(`[nginxService] initializeOnStartup: removed orphaned config ${filename}`);
      } catch (delErr) {
        console.error(`[nginxService] initializeOnStartup: failed to remove orphan ${filename}: ${delErr.message}`);
      }
    }
  }

  // Step 4: validate and reload
  try {
    await validateAndReload();
  } catch (err) {
    console.error(`[nginxService] initializeOnStartup: nginx test/reload failed: ${err.message}`);
  }
}

module.exports = {
  addProjectConfig,
  removeProjectConfig,
  removeMultipleProjectConfigs,
  initializeOnStartup,
};
